# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_department_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='StartDate',
            field=models.DateField(blank=True),
        ),
    ]
