# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190427_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
